### ISSUE TITLE
Unable to start vimiv with "-f" flag

### ISSUE THREAD

**Issue by Pro-Prietary** [karlch/vimiv#57] opened 2017-12-06 03:59 UTC
Incoming terminal output

```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vimiv/app.py", line 183, in activate_vimiv
    self._init_widgets()
  File "/usr/lib/python3.6/site-packages/vimiv/app.py", line 373, in _init_widgets
    self["window"] = Window(self)
  File "/usr/lib/python3.6/site-packages/vimiv/window.py", line 41, in __init__
    self.toggle_fullscreen()
  File "/usr/lib/python3.6/site-packages/vimiv/window.py", line 56, in toggle_fullscreen
    if self.get_window().get_state() & Gdk.WindowState.FULLSCREEN:
AttributeError: 'NoneType' object has no attribute 'get_state'```

Running this from Manjaro 17.1 XFCE

**Comment by karlch** [comment] 2017-12-06 08:03
Can reproduce it on arch, thanks for reporting.

Seems to be rather simple to fix but it looks like more things broke. Will have to investigate a bit further and possibly release another follow-up.

**Comment by karlch** [comment] 2017-12-07 23:39
Should be fixed with 77d4a1a9eb8ab35af0872d8b953f86295335460f, would you mind testing?

**Comment by Pro-Prietary** [comment] 2017-12-08 05:51
Sorry, I don't know much about compiling from source.

**Comment by karlch** [comment] 2017-12-08 08:29
You could simply install the latest `vimiv-git` package from the AUR.

**Comment by Pro-Prietary** [comment] 2017-12-08 08:35
Works like a charm! Thanks!

**Comment by karlch** [comment] 2017-12-08 09:24
Perfect :smile:

**Closed by karlch** 2017-12-08 09:24 UTC
Labels: bug
